
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 31 15:31:29 EST 2015
//----------------------------------------------------

package compiler488.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 40;
  public static final int WHEN = 25;
  public static final int FUNCTION = 9;
  public static final int PUT = 19;
  public static final int L_PAREN = 26;
  public static final int INTEGER = 8;
  public static final int R_SQUARE = 29;
  public static final int GREATER = 33;
  public static final int R_PAREN = 27;
  public static final int MINUS = 38;
  public static final int LESS = 34;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int INTCONST = 42;
  public static final int OR = 3;
  public static final int COMMA = 35;
  public static final int R_CURLEY = 31;
  public static final int GET = 20;
  public static final int BEGIN = 11;
  public static final int YIELDS = 24;
  public static final int PLUS = 37;
  public static final int LOOP = 18;
  public static final int EXIT = 15;
  public static final int IF = 16;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int RETURN = 17;
  public static final int EQUAL = 32;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int IDENT = 41;
  public static final int TIMES = 39;
  public static final int ELSE = 13;
  public static final int SKIP = 23;
  public static final int L_SQUARE = 28;
  public static final int WHILE = 22;
  public static final int THEN = 21;
  public static final int TEXTCONST = 43;
  public static final int END = 14;
  public static final int L_CURLEY = 30;
  public static final int FALSE = 6;
  public static final int PROCEDURE = 10;
  public static final int DO = 12;
}

